dist: trusty

language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-linux-x86_64
  - sha256sum -c tools/bazel-4.0.0-linux-x86_64.sha256
  - sudo dpkg -i bazel-4.0.0-linux-x86_64

script:
  - bazel --bazelrc=tools/bazel.travis.rc build //src/main/...
  - bazel --bazelrc=tools/bazel.travis.rc test //src/test/...
