package(default_visibility = ["//visibility:public"])

java_library(
    name = "dao",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/realworld/proto:realworld_java_proto",
        "//src/main/realworld/proto/internal:internal_java_proto",
        "@com_google_guava_guava//jar",
    ],
)
