package(default_visibility = ["//visibility:public"])

java_library(
  name = "server",
  srcs = glob(["*.java"]),
  deps = [
    "@com_google_guava_guava//jar",
    "@com_google_inject_extensions_guice_multibindings//jar",
    "@com_google_inject_guice//jar",
  ],
)
